// Generated by BUCKLESCRIPT VERSION 1.7.2, PLEASE EDIT WITH CARE
'use strict';

var List                 = require("bs-platform/lib/js/list.js");
var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var Printf               = require("bs-platform/lib/js/printf.js");
var Random               = require("bs-platform/lib/js/random.js");
var Director             = require("./director.js");
var Pervasives           = require("bs-platform/lib/js/pervasives.js");
var Procedural_generator = require("./procedural_generator.js");

var loadCount = [0];

function load() {
  Random.self_init(/* () */0);
  var canvas_id = "canvas";
  var match = document.getElementById(canvas_id);
  var canvas = match !== null ? match : (Curry._1(Printf.printf(/* Format */[
                /* String_literal */Block.__(11, [
                    "cant find canvas ",
                    /* String */Block.__(2, [
                        /* No_padding */0,
                        /* String_literal */Block.__(11, [
                            " \n",
                            /* End_of_format */0
                          ])
                      ])
                  ]),
                "cant find canvas %s \n"
              ]), canvas_id), Pervasives.failwith("fail"));
  var context = canvas.getContext("2d");
  document.addEventListener("keydown", Director.keydown, true);
  document.addEventListener("keyup", Director.keyup, true);
  Procedural_generator.init(/* () */0);
  Director.update_loop(canvas, Procedural_generator.generate(2400, 256, context), /* tuple */[
        2400,
        256
      ]);
  console.log("asd");
  return /* () */0;
}

function inc_counter() {
  loadCount[0] = loadCount[0] + 1 | 0;
  if (loadCount[0] === 4) {
    return load(/* () */0);
  } else {
    return /* () */0;
  }
}

function preload() {
  return List.map(function (img_src) {
              var img_src$1 = "sprites/" + img_src;
              var img = document.createElement("img");
              img.src = img_src$1;
              img.addEventListener("load", function () {
                    inc_counter(/* () */0);
                    return true;
                  }, true);
              return /* () */0;
            }, /* :: */[
              "blocks.png",
              /* :: */[
                "items.png",
                /* :: */[
                  "enemies.png",
                  /* :: */[
                    "mario-small.png",
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

window.onload = function () {
  preload(/* () */0);
  return true;
};

var Html = 0;

var Pg = 0;

var imgsToLoad = 4;

var level_width = 2400;

var level_height = 256;

exports.Html         = Html;
exports.Pg           = Pg;
exports.loadCount    = loadCount;
exports.imgsToLoad   = imgsToLoad;
exports.level_width  = level_width;
exports.level_height = level_height;
exports.load         = load;
exports.inc_counter  = inc_counter;
exports.preload      = preload;
/*  Not a pure module */
