// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';


function eq_dir_1d(x, y) {
  if (x !== 0) {
    return +(y === /* Right */1);
  } else {
    return +(y === /* Left */0);
  }
}

export {
  eq_dir_1d ,
  
}
/* No side effect */
