// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';


function eq_checkloc(param, param$1) {
  if (param[0] === param$1[0]) {
    return +(param[1] === param$1[1]);
  } else {
    return /* false */0;
  }
}

function max_float(a, b) {
  if (a > b) {
    return a;
  } else {
    return b;
  }
}

function min_float(a, b) {
  if (a < b) {
    return a;
  } else {
    return b;
  }
}

export {
  eq_checkloc ,
  max_float   ,
  min_float   ,
  
}
/* No side effect */
